spring:
   h2:
      console:
         enabled: true
   datasource:
      url: jdbc:h2:mem:features-db
      username: testuser
      password: testpassword
   jpa:
      hibernate:
#        Below "ddl-auto: create" is to be used only for testing
         ddl-auto: create
      properties:
         hibernate:
            dialect: org.hibernate.dialect.H2Dialect
            jdbc:
               lob:
                  non_contextual_creation: true